name: pkgraph
version: 1.0.0
description: Studying and visualizing Workiva dependencies.
author: George Lesica <george.lesica@workiva.com>

environment:
  sdk: ^2.0.0

dependencies:
  args: ^1.5.1
  http: ^0.12.0
  path: ^1.6.2
  pub_semver: ^1.4.2
  json_annotation: ^2.0.0
  yaml: ^2.1.15

dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
  test: ^1.0.0
