name: pkgraph
version: 1.0.0
description: Studying and visualizing Workiva dependencies.
author: George Lesica <george.lesica@workiva.com>

environment:
  sdk: ^2.0.0

dependencies:
  http: ^0.12.0
  pub_semver: ^1.4.2
  json_annotation: ^2.0.0

dev_dependencies:
  build_runner: ^1.0.0
  dart_dev: ^2.0.0
  dart_style: ^1.0.9
  json_serializable: ^2.0.0
  test: ^1.0.0
